### PR TITLE
Pass filename into stylus.render

### PR DESCRIPTION
**Pull request by cray0000**
This allows @import and @require to properly work

### CODE REVIEW

**Comment by kristerkari** [comment]
Thanks a lot!

**Comment by kristerkari** [comment]
I released this fix in v1.0.1, thanks again @cray0000!

**Comment by cray0000** [comment]
@kristerkari, awesome!
Another useful feature would be to allow to specify a particular file to import when compiling ANY `.styl` file.
This is useful when you have a library of global variables (website palette colors, etc.), mixins and functions which you want to be able to use in any component.
Like `_ButtonColors.scss` in your example, but for global variables, instead of a particular component-level variables.

I'll add that feature (to be able to pass an array of "includes" as an option) and will create another pull request.

**Comment by kristerkari** [comment]
Sounds good. I don't use Stylus myself, but I'm open to adding any features to the transformer, so just make a PR if you see that something is missing.

I'm still looking to find a clean way to add custom user options for React Native / Metro packager transformer functions. That would make giving user options much cleaner.

**Pull request merged**
